myfirstproject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('survey/',include('survey.urls')),
    path('admin/', admin.site.urls),
]

survey/urls.py
from django.urls import path
from . import views


#survey/5/
#survey/5/result
#survey/5/vote
app_name = "survey"
urlpatterns = [
                path('',views.index, name='index'),
                path('<int:question_id>/',views.detail,name = 'detail'),
                path('<int:question_id>/result/',views.result,name='result'),
                path('<int:question_id>/vote/',views.vote,name='vote'),
]

survey/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now()-datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

survey/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse

from .models import Question

# Create your views here.

def index(request):
    latest_question_list= Question.objects.all()
    context = {'latest_question_list': latest_question_list}
    return render(request, 'index.html', context)

def detail(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request,'detail.html',{'question': question})

    

def result(request,question_id):
    response = f"You are looking at the result of question {question_id}."
    return HttpResponse(response)

def vote(request,question_id):
    return HttpResponse(f"Your voting on question {question_id}")

survey/templates/detail.html
{% extends "base.html" %}
{% block content %}

     <h1>{{ question.question_text }}</h1>
       <ul>
       {% for choice in question.choice_set.all %}
         <li>{{ choice.choice_text }}</li>
       {% endfor %}
       </ul>

{% endblock %}

survey/templates/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />

     <h1>Question</h1>
        {% if latest_question_list %}
        <ul>
          {% for question in latest_question_list %}
           <!------ <li><a href="/survey/{{question_id}}/">{{question.question_text}}</a></li>-->
          <li>
            <a href="{% url 'survey:detail' question_id %}">{{question.question_text}}</a>
          </li>
           {% endfor %}
        </ul>
        {% else %}
          <p>NO Survey Available</p>
        {% endif %}
        

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no">
    
       <!-- Bootstrap CSS -->
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

       <title>Hello, World</title>
  </head>
  <body>

        {% block content %}
        {% endblock %}
    



        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    
   </body>
</html>